name: Laravel CI with Sail

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker environment
      run: docker-compose -f docker-compose.ci.yml up -d
    - name: Setup Laravel environment
      run: |
        cp .env.example .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=laravel" >> .env
        echo "DB_USERNAME=root" >> .env
        echo "DB_PASSWORD=secret" >> .env
        docker-compose -f docker-compose.ci.yml exec app php artisan key:generate
    - name: Install dependencies
      run: docker-compose -f docker-compose.ci.yml exec app composer install -v
    - name: update dependencies
      run: docker-compose -f docker-compose.ci.yml exec app composer update
    - name: Run migrations
      run: php artisan migrate
    - name: Run tests
      run: ./vendor/bin/phpunit
    - name: Turn down
      if: always()
      run: docker-compose -f docker-compose.ci.yml down
