name: Laravel CI with Sail

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker environment
      run: docker-compose -f docker-compose.ci.yml up -d
    - name: Install dependencies
      run: docker-compose exec app composer install
    - name: Run migrations
      run: docker-compose exec app php artisan migrate
    - name: Run tests
      run: docker-compose exec app vendor/bin/phpunit
      if: always()
    - name: Turn down
      run: docker-compose -f docker-compose.ci.yml down
