name: Laravel CI with Sail

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306

    steps:
    - uses: actions/checkout@v2

    - name: Setup Docker Environment
      run: docker-compose -f docker-compose.ci.yml up -d

    - name: Install Composer Dependencies
      run: docker-compose exec laravel.test composer install --prefer-dist --no-progress --no-suggest

    - name: Copy .env
      run: docker-compose exec laravel.test php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Generate key
      run: docker-compose exec laravel.test php artisan key:generate

    - name: Run Migrations
      run: docker-compose exec laravel.test php artisan migrate

    - name: Run Tests
      run: docker-compose exec laravel.test vendor/bin/phpunit

    - name: Shutdown Docker Environment
      if: always()
      run: docker-compose -f docker-compose.ci.yml down
